"use client";

import Link from "next/link";
import { useState } from "react";
import { FileUp, FlaskConical, LayoutGrid, List } from "lucide-react";
import { Badge, Callout, Card, CardBody, CardHeader, KeyValue, LoadingState, PageHeader, StatusBadge } from "@/components/ui";
import { PlantTopology } from "@/components/topology/PlantTopology";
import { PlantList } from "@/components/topology/PlantList";
import { SituationPanel } from "@/components/topology/SituationPanel";
import { AttentionQueue } from "@/components/topology/AttentionQueue";
import { COVERAGE_LEGEND } from "@/components/topology/plantMeta";
import { ASSETS, CELLS } from "@/lib/domain/plant";
import { SCENARIO_BY_ID } from "@/lib/simulation/scenarios";
import { useMediaQuery } from "@/lib/ui/useMediaQuery";
import { cn, formatDuration, formatIst } from "@/lib/util";
import { useApp } from "@/store/app";

const linkButton = "inline-flex h-8 items-center justify-center gap-1.5 rounded-md border px-3 text-sm font-medium whitespace-nowrap transition-colors";

function modeLabel(mode: string): { text: string; tone: "amber" | "accent" | "grey" } {
  if (mode === "IMPORTED_REPLAY") return { text: "IMPORTED REPLAY", tone: "accent" };
  if (mode === "LIVE_ADAPTER") return { text: "LIVE", tone: "grey" };
  return { text: "SIMULATION", tone: "amber" };
}

export default function PlantPage() {
  const snapshot = useApp((s) => s.snapshot);
  const workspace = useApp((s) => s.workspace);
  const knowledgeId = useApp((s) => s.activeKnowledgeVersionId);
  const storage = useApp((s) => s.storage);
  const small = useMediaQuery("(max-width: 767px)");
  const [viewPref, setViewPref] = useState<"graph" | "list" | null>(null);
  const [focusIncidentId, setFocusIncidentId] = useState<string | null>(null);
  const view = viewPref ?? (small ? "list" : "graph");

  if (!snapshot) return <LoadingState label="Starting the simulation engine…" />;

  const mode = modeLabel(snapshot.mode);
  const scenario = snapshot.scenarioId ? SCENARIO_BY_ID[snapshot.scenarioId] : undefined;
  const coverageCounts = Object.fromEntries(COVERAGE_LEGEND.map((c) => [c.value, ASSETS.filter((a) => a.coverage === c.value).length])) as Record<string, number>;

  return (
    <div>
      <PageHeader
        title="Plant"
        description={`${workspace.name} (fictional). ${snapshot.mode === "IMPORTED_REPLAY" ? "Observations come from an imported trace and are never modified." : "Observations are generated by a deterministic simulation in this browser; this is not a factory connection."}`}
        badges={
          <>
            <Badge tone={mode.tone}>{mode.text}</Badge>
            <Badge tone="grey">LIVE: Not configured</Badge>
            {snapshot.clock.viewingPast ? <Badge tone="grey">viewing past</Badge> : null}
          </>
        }
        actions={
          <>
            <Link href="/lab" className={cn(linkButton, "border-border bg-surface-2 text-text hover:bg-border/60")}>
              <FlaskConical size={15} aria-hidden /> Explore demo
            </Link>
            <Link href="/knowledge/sources?import=1" className={cn(linkButton, "border-accent bg-accent text-white hover:opacity-90")}>
              <FileUp size={15} aria-hidden /> Import factory files
            </Link>
          </>
        }
      />

      <div className="grid gap-3 xl:grid-cols-[minmax(0,1fr)_400px]">
        <Card className="min-w-0">
          <CardHeader
            title="Topology"
            description="Eighteen assets in five zones. Edges are published dependencies from the active knowledge version; status follows observed evidence, never absence of alarms."
            actions={
              <div role="group" aria-label="Topology view" className="inline-flex rounded-md border border-border p-0.5">
                <button type="button" aria-pressed={view === "graph"} onClick={() => setViewPref("graph")} className={cn("inline-flex items-center gap-1 rounded px-2 py-1 text-[12px]", view === "graph" ? "bg-surface-2 font-medium" : "text-muted hover:text-text")}>
                  <LayoutGrid size={13} aria-hidden /> Graph
                </button>
                <button type="button" aria-pressed={view === "list"} onClick={() => setViewPref("list")} className={cn("inline-flex items-center gap-1 rounded px-2 py-1 text-[12px]", view === "list" ? "bg-surface-2 font-medium" : "text-muted hover:text-text")}>
                  <List size={13} aria-hidden /> List
                </button>
              </div>
            }
          />
          <CardBody>
            {view === "graph" ? <PlantTopology snapshot={snapshot} focusIncidentId={focusIncidentId} onFocusIncidentChange={setFocusIncidentId} /> : <PlantList snapshot={snapshot} focusIncidentId={focusIncidentId} />}
          </CardBody>
        </Card>

        <div className="flex min-w-0 flex-col gap-3">
          <SituationPanel snapshot={snapshot} />
          <AttentionQueue snapshot={snapshot} selectedId={focusIncidentId} onSelect={setFocusIncidentId} />

          <Card>
            <CardHeader title="Cells" description="Operating context at the cursor. Commanded speed is what the recipe or operator asked for, not a measurement." />
            <CardBody className="grid gap-3 sm:grid-cols-2 xl:grid-cols-1">
              {CELLS.map((c) => {
                const cell = snapshot.cells[c.id];
                return (
                  <div key={c.id} className="rounded-md border border-border px-3 py-2">
                    <div className="flex flex-wrap items-center justify-between gap-2">
                      <Link href={`/plant/${c.cncId}`} className="text-[13px] font-semibold hover:underline">
                        {c.name} <span className="mono font-normal text-muted">{c.id}</span>
                      </Link>
                      <div className="flex flex-wrap gap-1">
                        <Badge tone="grey">{cell?.phase ?? "UNCLASSIFIED"}</Badge>
                        {cell?.interrupted ? <Badge tone="red">interrupted</Badge> : null}
                      </div>
                    </div>
                    <KeyValue
                      className="mt-1.5"
                      items={[
                        { k: "Recipe", v: <span className="mono">{cell?.recipe ?? "UNKNOWN"}</span> },
                        { k: "Mode", v: cell?.mode ?? "UNKNOWN" },
                        {
                          k: "Commanded speed",
                          v: (
                            <span className="inline-flex flex-wrap items-center gap-1.5">
                              <span className="tnum">{cell?.commandedSpeedRpm ?? 0} rpm</span>
                              {cell?.overrideActive ? <Badge tone="amber">override</Badge> : null}
                            </span>
                          ),
                        },
                        { k: "Cycle count", v: <span className="tnum">{cell?.cycleCount ?? 0}</span> },
                        { k: "Cycle", v: <span className="mono">{cell?.cycleId || "—"}</span> },
                      ]}
                    />
                  </div>
                );
              })}
            </CardBody>
          </Card>

          <Card>
            <CardHeader title="Simulation" description="Deterministic for a given seed and scenario. Playback speed never changes observation values." actions={<Badge tone={mode.tone}>{mode.text}</Badge>} />
            <CardBody>
              <KeyValue
                items={[
                  { k: "Seed", v: <span className="tnum">{snapshot.seed ?? "—"}</span> },
                  { k: "Scenario", v: scenario ? `${scenario.number}. ${scenario.title}` : (snapshot.scenarioId ?? "—") },
                  { k: "Simulation clock", v: <span className="tnum">{formatIst(snapshot.clock.cursorMs, { date: true, seconds: true })} IST</span> },
                  { k: "Live edge", v: <span className="tnum">{formatIst(snapshot.clock.liveMs, { seconds: true })}{snapshot.clock.viewingPast ? ` (cursor ${formatDuration(snapshot.clock.liveMs - snapshot.clock.cursorMs)} behind)` : ""}</span> },
                  { k: "Playback", v: <span className="tnum">{snapshot.clock.running ? `running · ${snapshot.clock.speed}×` : "paused"}</span> },
                  { k: "Observations", v: <span className="tnum">{snapshot.stats.observations.toLocaleString("en-IN")} across {snapshot.stats.tags} tags</span> },
                  { k: "Diagnosis runs", v: <span className="tnum">{snapshot.stats.diagnosisRuns}</span> },
                  { k: "Knowledge", v: <span className="mono">{knowledgeId}</span> },
                  { k: "Live adapter", v: <span><StatusBadge value="UNAVAILABLE" className="mr-1" />Not configured — {snapshot.liveAdapter.reason}</span> },
                  { k: "Storage", v: storage.available ? (storage.readOnly ? "Read-only tab" : "Stored in this browser — not cloud-synced") : `Unavailable${storage.reason ? ` — ${storage.reason}` : ""}` },
                ]}
              />
              {snapshot.importInfo ? (
                <Callout tone="accent" title="Imported replay" className="mt-3">
                  {snapshot.importInfo.fileNames.join(", ")}
                  {snapshot.importInfo.limitations.length ? <ul className="mt-1 list-disc pl-4 text-[12px]">{snapshot.importInfo.limitations.map((l, i) => <li key={i}>{l}</li>)}</ul> : null}
                </Callout>
              ) : null}
            </CardBody>
          </Card>

          <Card>
            <CardHeader title="Model coverage" description="What the approved knowledge can and cannot say about each asset. Coverage is a property of the model, not of the equipment." />
            <CardBody>
              <ul className="space-y-2">
                {COVERAGE_LEGEND.map((c) => (
                  <li key={c.value} className="text-[13px]">
                    <div className="flex flex-wrap items-center gap-2">
                      <span className="font-medium">{c.label}</span>
                      <span className="tnum text-[12px] text-muted">
                        {coverageCounts[c.value] ?? 0} asset{coverageCounts[c.value] === 1 ? "" : "s"}
                      </span>
                    </div>
                    <p className="text-[12px] text-muted">{c.explanation}</p>
                  </li>
                ))}
              </ul>
            </CardBody>
          </Card>
        </div>
      </div>
    </div>
  );
}
