"use client";

import "@xyflow/react/dist/style.css";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { Background, Controls, Handle, MarkerType, MiniMap, Position, ReactFlow, type Connection, type Edge, type Node, type NodeChange, applyNodeChanges } from "@xyflow/react";
import { Bot, Box, Cable, ChevronDown, ChevronRight, CircuitBoard, Cog, Cpu, Gauge, Library, MonitorUp, Moon, Plus, Redo2, Save, Search, ShieldAlert, Undo2, Zap } from "lucide-react";
import { approveProposalChange, createCadDocument, deterministicDraft, rejectProposalChange, validateConnection, type CadAsset, type CadConnection, type CadDocument, type CadProposal, type CadTerminal, type CadView } from "@/lib/cad";
import { Badge, Button, Input, StatusBadge, Textarea } from "@/components/ui";
import styles from "./cad-workbench.module.css";

type DesktopAdapter = { workspaceLoad?: () => Promise<CadDocument | null>; workspaceSave?: (document: CadDocument, expectedRevision: number) => Promise<CadDocument | void>; agentDraft?: (request: string, document: CadDocument) => Promise<CadProposal>; modelStatus?: () => Promise<{ available?: boolean; state?: string }> };
const desktop = () => (typeof window === "undefined" ? undefined : (window as unknown as { plantlensDesktop?: DesktopAdapter }).plantlensDesktop);
const STORAGE_KEY = "plantlens.cad.workspace.v1";
const views: Array<{ id: CadView; label: string; note: string }> = [
  { id: "signal", label: "Signal wiring", note: "I/O and read-only telemetry" },
  { id: "electrical", label: "Electrical schematic", note: "Illustrative template" },
  { id: "presentation", label: "Presentation twin", note: "Operational overview" },
];
const iconFor = (kind: CadAsset["kind"], size = 20) => {
  const props = { size, strokeWidth: 1.6 }; if (kind === "motor") return <Cog {...props}/>; if (kind === "sensor") return <Gauge {...props}/>;
  if (kind === "drive") return <Zap {...props}/>; if (kind === "controller") return <Cpu {...props}/>; if (kind === "protection") return <ShieldAlert {...props}/>;
  if (kind === "ground") return <Cable {...props}/>; if (kind === "isolation") return <CircuitBoard {...props}/>; return <Box {...props}/>;
};

type AssetNodeData = { asset: CadAsset; terminals: CadTerminal[]; view: CadView; selected?: boolean };
function AssetNode({ data }: { data: AssetNodeData }) {
  const present = data.view === "presentation";
  return <div className={`${styles.assetNode} ${present ? styles.presentationNode : ""}`} aria-label={`${data.asset.id} ${data.asset.name}`}>
    <div className={styles.assetHead}><span className={styles.assetIcon}>{iconFor(data.asset.kind, present ? 28 : 18)}</span><div><b>{data.asset.id}</b><span>{data.asset.name}</span></div></div>
    {present ? <div className={styles.metric}><span>Operational state</span><strong>{data.asset.kind === "sensor" ? "6.2 bar" : data.asset.kind === "drive" ? "42.0 Hz" : "Normal"}</strong><small>SIMULATED · GOOD</small></div> : <div className={styles.terminals}>{data.terminals.map(t => <div className={styles.terminal} key={t.id}>
      {(t.direction === "in" || t.direction === "bidirectional") && <Handle id={t.id} type="target" position={Position.Left} className={styles.handle}/>}<span>{t.name}</span><small>{t.signalType}{t.unit ? ` · ${t.unit}` : ""}</small>{(t.direction === "out" || t.direction === "bidirectional") && <Handle id={t.id} type="source" position={Position.Right} className={styles.handle}/>}</div>)}</div>}
  </div>;
}
const nodeTypes = { asset: AssetNode };

function loadBrowser(): CadDocument | null { try { const value = localStorage.getItem(STORAGE_KEY); return value ? JSON.parse(value) as CadDocument : null; } catch { return null; } }
function PanelTitle({ children }: { children: React.ReactNode }) { return <h2 className={styles.panelTitle}>{children}</h2>; }

export function CadWorkbench() {
  const [document, setDocument] = useState<CadDocument>(() => createCadDocument()); const [view, setView] = useState<CadView>("signal");
  const [selected, setSelected] = useState<{ type: "asset" | "connection"; id: string } | null>(null); const [query, setQuery] = useState("");
  const [diagnosticsOpen, setDiagnosticsOpen] = useState(true); const [draftOpen, setDraftOpen] = useState(false); const [request, setRequest] = useState("");
  const [message, setMessage] = useState("Opening local workspace…"); const [modelState, setModelState] = useState("Checking local model"); const [busy, setBusy] = useState(false);
  const undo = useRef<CadDocument[]>([]); const redo = useRef<CadDocument[]>([]); const persistedRevision = useRef(0);
  const replace = useCallback((next: CadDocument, history = true) => { setDocument(current => { if (history) { undo.current.push(current); redo.current = []; } return next; }); }, []);
  useEffect(() => { void (async () => { const api = desktop(); let loaded: CadDocument | null = null; try { loaded = api?.workspaceLoad ? await api.workspaceLoad() : loadBrowser(); } catch { loaded = loadBrowser(); }
    if (loaded?.schemaVersion === 1) { setDocument(loaded); persistedRevision.current = loaded.revision; } setMessage(loaded ? "Workspace restored" : "New browser-local workspace");
    try { const status = await api?.modelStatus?.(); setModelState(status?.available ? "Local model ready" : status?.state || "Local AI unavailable"); } catch { setModelState("Local AI unavailable"); }
  })(); }, []);
  const save = useCallback(async () => { setBusy(true); try { const api = desktop(); if (api?.workspaceSave) { const saved = await api.workspaceSave(document, persistedRevision.current); persistedRevision.current = saved?.revision ?? persistedRevision.current + 1; if (saved) setDocument(saved); setMessage("Saved to desktop workspace"); } else { localStorage.setItem(STORAGE_KEY, JSON.stringify(document)); setMessage("Saved in this browser"); } } catch (error) { setMessage(error instanceof Error ? `Save blocked: ${error.message}` : "Save blocked by revision conflict"); } finally { setBusy(false); } }, [document]);
  const doUndo = () => setDocument(current => { const prior = undo.current.pop(); if (!prior) return current; redo.current.push(current); return prior; });
  const doRedo = () => setDocument(current => { const next = redo.current.pop(); if (!next) return current; undo.current.push(current); return next; });
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (!(event.ctrlKey || event.metaKey)) return; if (event.key.toLowerCase() === "s") { event.preventDefault(); void save(); } if (event.key.toLowerCase() === "z") { event.preventDefault(); if (event.shiftKey) doRedo(); else doUndo(); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); });
  const nodes = useMemo<Node<AssetNodeData>[]>(() => document.placements.filter(p => p.view === view).map(p => { const asset = document.assets.find(a => a.id === p.assetId)!; return { id: asset.id, type: "asset", position: { x: p.x, y: p.y }, data: { asset, terminals: document.terminals.filter(t => t.assetId === asset.id), view }, selected: selected?.type === "asset" && selected.id === asset.id }; }), [document, view, selected]);
  const edges = useMemo<Edge[]>(() => view === "presentation" ? [] : document.connections.filter(c => c.view === view).map(c => ({ id: c.id, source: document.terminals.find(t => t.id === c.sourceTerminalId)!.assetId, target: document.terminals.find(t => t.id === c.targetTerminalId)!.assetId, sourceHandle: c.sourceTerminalId, targetHandle: c.targetTerminalId, type: "smoothstep", label: `${c.signalType}${c.unit ? ` · ${c.unit}` : ""}`, markerEnd: { type: MarkerType.ArrowClosed }, animated: c.signalType === "telemetry", style: { stroke: c.verification === "TEMPLATE" ? "var(--amber)" : c.signalType === "earth" ? "var(--green)" : "var(--accent)", strokeDasharray: c.verification === "VERIFIED" ? undefined : "6 4" } })), [document, view]);
  const onNodesChange = useCallback((changes: NodeChange[]) => { const changed = applyNodeChanges(changes, nodes); const positions = new Map(changed.map(n => [n.id, n.position])); if (!changes.some(c => c.type === "position" && !c.dragging)) return; replace({ ...document, revision: document.revision + 1, placements: document.placements.map(p => p.view === view && positions.has(p.assetId) ? { ...p, ...positions.get(p.assetId)! } : p) }); }, [document, nodes, replace, view]);
  const onConnect = useCallback((connection: Connection) => { if (view === "presentation" || !connection.sourceHandle || !connection.targetHandle) return; const source = document.terminals.find(t => t.id === connection.sourceHandle); if (!source) return; const candidate = { view, sourceTerminalId: connection.sourceHandle, targetTerminalId: connection.targetHandle, signalType: source.signalType, unit: source.unit }; const errors = validateConnection(document, candidate); if (errors.length) { setMessage(`Connection blocked: ${errors.join(" ")}`); return; }
    const item: CadConnection = { ...candidate, id: `C-${Date.now()}`, verification: view === "electrical" ? "TEMPLATE" : "UNVERIFIED" }; replace({ ...document, revision: document.revision + 1, connections: [...document.connections, item] }); setSelected({ type: "connection", id: item.id }); setMessage(view === "electrical" ? "Template connection added; terminal assignments remain unverified" : "Unverified connection added"); }, [document, replace, view]);
  const addToView = (asset: CadAsset) => { if (document.placements.some(p => p.view === view && p.assetId === asset.id)) { setSelected({ type: "asset", id: asset.id }); return; } replace({ ...document, revision: document.revision + 1, placements: [...document.placements, { assetId: asset.id, view, x: 100, y: 100 }] }); setSelected({ type: "asset", id: asset.id }); };
  const runDraft = async (event: FormEvent) => { event.preventDefault(); if (!request.trim()) return; setBusy(true); try { const api = desktop(); const proposal = api?.agentDraft ? await api.agentDraft(request, document) : deterministicDraft(request, document); replace({ ...document, proposals: [proposal, ...document.proposals] }); setMessage(proposal.source === "LOCAL_MODEL" ? "Local model draft ready for review" : proposal.message || "Offline deterministic draft ready"); setRequest(""); } catch (error) { setMessage(`Draft failed: ${error instanceof Error ? error.message : "invalid structured output"}`); } finally { setBusy(false); } };
  const approve = (proposalId: string, changeId: string) => replace(approveProposalChange(document, proposalId, changeId));
  const reject = (proposalId: string, changeId: string) => replace(rejectProposalChange(document, proposalId, changeId));
  const editChange = (proposalId: string, changeId: string) => { const change = document.proposals.find(p => p.id === proposalId)?.changes.find(c => c.id === changeId); if (!change) return; const value = window.prompt(change.kind === "rename_asset" ? "New asset name" : "Edit structured asset JSON", change.value); if (value === null || value === change.value) return; replace({ ...document, proposals: document.proposals.map(p => p.id !== proposalId ? p : { ...p, changes: p.changes.map(c => c.id === changeId ? { ...c, value, summary: `${c.kind.replace("_", " ")}: ${value}` } : c) }) }); };
  const selectedAsset = selected?.type === "asset" ? document.assets.find(a => a.id === selected.id) : undefined; const selectedConnection = selected?.type === "connection" ? document.connections.find(c => c.id === selected.id) : undefined;
  const library = document.assets.filter(a => `${a.id} ${a.name} ${a.kind}`.toLowerCase().includes(query.toLowerCase()));
  return <main className={styles.workbench} data-view={view}>
    <header className={styles.topbar}><div className={styles.brand}><CircuitBoard size={20}/><div><b>PlantLens CAD</b><span>{document.name} · rev {document.revision}</span></div></div><div className={styles.toolbar}><Link href="/plant">Plant</Link><Link href="/live">Live</Link><Link href="/explain">Explain</Link><Button size="sm" variant="ghost" aria-label="Toggle theme" onClick={() => window.document.documentElement.setAttribute("data-theme", window.document.documentElement.getAttribute("data-theme") === "dark" ? "light" : "dark")}><Moon size={14}/></Button><Button size="sm" variant="ghost" onClick={doUndo} aria-label="Undo"><Undo2 size={15}/></Button><Button size="sm" variant="ghost" onClick={doRedo} aria-label="Redo"><Redo2 size={15}/></Button><Button size="sm" onClick={() => void save()} disabled={busy}><Save size={14}/>Save</Button><Button size="sm" variant="primary" onClick={() => setDraftOpen(v => !v)}><Bot size={15}/>Draft change</Button></div></header>
    <nav className={styles.viewTabs} aria-label="Engineering views">{views.map(v => <button key={v.id} onClick={() => { setView(v.id); setSelected(null); }} aria-current={view === v.id ? "page" : undefined}><span>{v.label}</span><small>{v.note}</small></button>)}</nav>
    <div className={styles.mainGrid}><aside className={styles.leftPanel}><PanelTitle>Project</PanelTitle><div className={styles.tree}><button><ChevronDown size={14}/>PL-CAD-001</button>{views.map(v => <button className={view === v.id ? styles.activeTree : ""} key={v.id} onClick={() => setView(v.id)}><span className={styles.branch}/>{v.id === "signal" ? <Cable size={14}/> : v.id === "electrical" ? <Zap size={14}/> : <MonitorUp size={14}/>} {v.label}</button>)}</div><div className={styles.divider}/><PanelTitle>Component library</PanelTitle><label className={styles.search}><Search size={14}/><Input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search components" aria-label="Search component library"/></label><div className={styles.library}>{library.map(asset => <button key={asset.id} onClick={() => addToView(asset)}><span>{iconFor(asset.kind)}</span><span><b>{asset.id}</b><small>{asset.name}</small></span><Plus size={14}/></button>)}</div></aside>
    <section className={styles.canvas} aria-label={`${views.find(v => v.id === view)?.label} canvas`}><div className={styles.canvasBanner}>{view === "electrical" ? <><ShieldAlert size={14}/><b>ILLUSTRATIVE TEMPLATE</b> Exact equipment models, terminals, conductor sizes, and protective ratings require manufacturer evidence.</> : view === "presentation" ? <><MonitorUp size={14}/>Presentation twin · simulated measurements</> : <><Cable size={14}/>Typed signal paths · select a connection to inspect evidence</>}</div><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onConnect={onConnect} onNodeClick={(_, n) => setSelected({ type: "asset", id: n.id })} onEdgeClick={(_, e) => setSelected({ type: "connection", id: e.id })} fitView snapToGrid snapGrid={[20,20]} selectionOnDrag panOnScroll multiSelectionKeyCode="Shift" deleteKeyCode={null} defaultEdgeOptions={{ type: "smoothstep" }} colorMode="system"><Background gap={20} size={1}/><Controls/><MiniMap pannable zoomable/></ReactFlow></section>
    <aside className={styles.inspector}><PanelTitle>Inspector</PanelTitle>{selectedAsset ? <AssetInspector key={selectedAsset.id} asset={selectedAsset} document={document} onRename={name => replace({ ...document, revision: document.revision + 1, assets: document.assets.map(a => a.id === selectedAsset.id ? { ...a, name } : a) })}/> : selectedConnection ? <ConnectionInspector connection={selectedConnection} document={document} onDelete={() => { replace({ ...document, revision: document.revision + 1, connections: document.connections.filter(c => c.id !== selectedConnection.id) }); setSelected(null); }}/> : <div className={styles.empty}><Library size={26}/><p>Select an asset or connection</p><span>Its shared ID and engineering metadata will appear here.</span></div>}</aside></div>
    {draftOpen && <section className={styles.draftPanel}><div><PanelTitle>Natural-language draft</PanelTitle><p>Suggestions never apply automatically. Review and approve each item.</p></div><form onSubmit={runDraft}><Textarea value={request} onChange={e => setRequest(e.target.value)} rows={2} placeholder="Rename M-101 to Main pump motor"/><Button variant="primary" type="submit" disabled={busy || !request.trim()}>Draft</Button></form><div className={styles.proposals}>{document.proposals.slice(0,3).map(p => <article key={p.id}><div><StatusBadge value={p.status}/><Badge tone={p.source === "LOCAL_MODEL" ? "accent" : "grey"}>{p.source.replace("_", " ")}</Badge><span>{p.request}</span></div>{p.message && <p>{p.message}</p>}{p.changes.map(c => <div className={styles.change} key={c.id}><span><b>{c.kind.replace("_", " ")}</b>{c.summary}</span><StatusBadge value={c.status}/>{c.status === "PENDING" ? <><Button size="sm" variant="primary" onClick={() => approve(p.id, c.id)}>Approve item</Button><Button size="sm" variant="ghost" onClick={() => editChange(p.id, c.id)}>Edit item</Button><Button size="sm" variant="ghost" onClick={() => reject(p.id, c.id)}>Reject</Button></> : null}</div>)}</article>)}</div></section>}
    <section className={styles.diagnostics}><button onClick={() => setDiagnosticsOpen(v => !v)}>{diagnosticsOpen ? <ChevronDown size={14}/> : <ChevronRight size={14}/>}Diagnostics <Badge tone="green">0 errors</Badge></button>{diagnosticsOpen && <div><span><i className={styles.ok}/>Document schema v{document.schemaVersion} valid</span><span><i className={styles.warn}/>{document.connections.filter(c => c.verification !== "VERIFIED").length} unverified/template connections</span><span><i className={styles.info}/>{modelState}</span><span className={styles.status}>{message}</span></div>}</section>
  </main>;
}

function AssetInspector({ asset, document, onRename }: { asset: CadAsset; document: CadDocument; onRename: (name: string) => void }) { const [name, setName] = useState(asset.name); const terminals = document.terminals.filter(t => t.assetId === asset.id); return <div className={styles.inspectBody}><div className={styles.heroIcon}>{iconFor(asset.kind, 32)}</div><Badge tone="accent">{asset.kind.toUpperCase()}</Badge><h3>{asset.id}</h3><label>Name<Input value={name} onChange={e => setName(e.target.value)} onBlur={() => name.trim() && name !== asset.name && onRename(name.trim())}/></label><dl><dt>Description</dt><dd>{asset.description}</dd><dt>Shared asset ID</dt><dd className="mono">{asset.id}</dd></dl><h4>Terminals</h4>{terminals.length ? terminals.map(t => <div className={styles.terminalCard} key={t.id}><b>{t.name}</b><span>{t.id}</span><small>{t.direction} · {t.signalType} {t.unit || ""}</small></div>) : <p className={styles.muted}>No terminals configured. Add verified terminal data before wiring.</p>}</div>; }
function ConnectionInspector({ connection, document, onDelete }: { connection: CadConnection; document: CadDocument; onDelete: () => void }) { const source = document.terminals.find(t => t.id === connection.sourceTerminalId)!; const target = document.terminals.find(t => t.id === connection.targetTerminalId)!; return <div className={styles.inspectBody}><StatusBadge value={connection.verification}/><h3>{connection.id}</h3><div className={styles.endpoint}><small>SOURCE</small><b>{source.assetId} · {source.name}</b><span>{source.id}</span></div><div className={styles.endpoint}><small>TARGET</small><b>{target.assetId} · {target.name}</b><span>{target.id}</span></div><dl><dt>Signal</dt><dd>{connection.signalType}</dd><dt>Units</dt><dd>{connection.unit || "—"}</dd><dt>Evidence</dt><dd>{connection.evidence || "No source evidence attached"}</dd></dl>{connection.verification === "TEMPLATE" && <p className={styles.warning}>Illustrative only. Do not use for construction or commissioning.</p>}<Button variant="danger" size="sm" onClick={onDelete}>Remove connection</Button></div>; }
