"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useMemo, useRef, useState, type ChangeEvent } from "react";
import { Download, FileUp, Play, Search, ShieldCheck, Wrench } from "lucide-react";
import { ASSET_BY_ID, TAGS, tagsForAsset } from "@/lib/domain/plant";
import { SCENARIOS, INTERVENTIONS, type InterventionId } from "@/lib/simulation/scenarios";
import { EVALUATION_SEEDS } from "@/lib/simulation/evaluation";
import { useApp } from "@/store/app";
import { Badge, Button, Card, CardBody, CardHeader, EmptyState, Input, LoadingState, PageHeader, Select, StatusBadge } from "@/components/ui";

const fmt = (ms?: number) => (ms ? new Intl.DateTimeFormat("en-IN", { dateStyle: "medium", timeStyle: "medium", timeZone: "Asia/Kolkata" }).format(ms) : "—");
const money = (paise: number) => new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(paise / 100);

function Metric({ label, value, note }: { label: string; value: string | number; note?: string }) {
  return <div className="rounded-lg border border-border bg-surface px-4 py-3"><p className="text-[12px] text-muted">{label}</p><p className="mt-1 text-xl font-semibold tabular-nums">{value}</p>{note ? <p className="mt-1 text-[11px] text-muted">{note}</p> : null}</div>;
}

export function AssetView({ id }: { id: string }) {
  const snapshot = useApp((s) => s.snapshot);
  const asset = ASSET_BY_ID[id];
  if (!asset) return <EmptyState title="Asset not found" description="This asset ID is not in the active plant registry." />;
  if (!snapshot) return <LoadingState label="Starting simulation engine…" />;
  const view = snapshot.assets[id];
  const incidents = snapshot.incidents.filter((i) => [...i.observedAssetIds, ...i.potentiallyAffectedAssetIds].includes(id));
  return <div><PageHeader title={`${id} · ${asset.name}`} description={asset.description} badges={<><StatusBadge value={view?.status} /><Badge tone="grey">{asset.kind.replace(/_/g, " ")}</Badge></>} />
    <div className="grid gap-3 lg:grid-cols-[1.5fr_1fr]"><Card><CardHeader title="Observed state" description="Engine-produced values at the current simulation cursor." /><CardBody className="grid gap-2 sm:grid-cols-2">{view?.headline.map((h) => <div key={h.tag} className="rounded-md bg-surface-2 p-3"><p className="mono text-[12px] text-muted">{h.tag}</p><p className="mt-1 text-lg tabular-nums">{String(h.value)} {h.unit}</p></div>)}</CardBody></Card>
    <Card><CardHeader title="Model coverage" /><CardBody><StatusBadge value={asset.coverage} /><p className="mt-3 text-sm text-muted">{asset.coverageReason}</p>{asset.parentId ? <p className="mt-2 text-sm">Subsystem of <Link className="text-accent" href={`/plant/${asset.parentId}`}>{asset.parentId}</Link></p> : null}</CardBody></Card></div>
    <Card className="mt-3"><CardHeader title="Registered tags" description={`${tagsForAsset(id).length} typed channels; unavailable values are never treated as zero.`} /><CardBody className="overflow-x-auto"><table><thead><tr><th>Tag</th><th>Type</th><th>Unit</th><th>Description</th></tr></thead><tbody>{tagsForAsset(id).map((t) => <tr key={t.id}><td className="mono">{t.name}</td><td>{t.valueType}</td><td>{t.unit ?? "—"}</td><td>{t.description}</td></tr>)}</tbody></table></CardBody></Card>
    <Card className="mt-3"><CardHeader title="Related incidents" /><CardBody>{incidents.length ? incidents.map((i) => <Link key={i.id} href={`/incidents/${i.id}`} className="mb-2 flex justify-between rounded-md border border-border p-3 hover:bg-surface-2"><span>{i.title}<span className="block mono text-[12px] text-muted">{i.id}</span></span><StatusBadge value={i.status} /></Link>) : <p className="text-sm text-muted">No incident currently touches this asset.</p>}</CardBody></Card></div>;
}

export function SourcesView() {
  const st = useApp();
  const input = useRef<HTMLInputElement>(null);
  const onFiles = async (e: ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files ?? []);
    await st.importFiles(await Promise.all(files.map(async (f) => ({ name: f.name, text: await f.text(), size: f.size }))));
    e.target.value = "";
  };
  return <div><PageHeader title="Knowledge sources" description="Parse local files, preserve provenance, and review every mapping before it can affect runtime conclusions." actions={<><input ref={input} className="hidden" type="file" multiple accept=".csv,.json,.txt,.st,.scl,.xml" onChange={onFiles}/><Button onClick={() => input.current?.click()}><FileUp size={15}/>Import factory files</Button><Button variant="primary" onClick={() => void st.loadSamplePack()}>Load sample factory pack</Button><Button onClick={() => void st.downloadSamplePack()}><Download size={15}/>Download pack</Button></>} />
    <div className="grid gap-3 sm:grid-cols-3"><Metric label="Source documents" value={st.sources.length}/><Metric label="Parsed records" value={st.parsedFiles.reduce((n,p) => n + (p.document.rowCount ?? 0),0)}/><Metric label="Pending trace mappings" value={st.pendingImports.length}/></div>
    {st.pendingImports.map((p) => <Card className="mt-3" key={p.fileId}><CardHeader title={p.fileName} description={`${p.rowCount} rows · imported data remains separate from simulation`} actions={<><Button onClick={() => st.previewPendingImport(p.fileId)}>Validate</Button><Button variant="primary" onClick={() => void st.commitPendingImport(p.fileId)}>Open replay</Button><Button variant="ghost" onClick={() => st.discardPendingImport(p.fileId)}>Discard</Button></>} /><CardBody><div className="overflow-x-auto"><table><thead><tr>{p.headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{p.preview.slice(0,5).map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c || <span className="text-muted">null</span>}</td>)}</tr>)}</tbody></table></div>{p.report ? <p className="mt-3 text-sm text-muted">Accepted {p.report.accepted}; invalid timestamps {p.report.invalidTimestamps}; duplicates {p.report.duplicates}; out of order {p.report.outOfOrder}; unknown units retained {p.report.unknownUnits.length}.</p>:null}</CardBody></Card>)}
    <Card className="mt-3"><CardHeader title="Source inventory" actions={<Button variant="primary" disabled={!st.parsedFiles.length} onClick={st.runPipeline}>Run local compilation</Button>} /><CardBody>{st.sources.length ? <div className="overflow-x-auto"><table><thead><tr><th>File</th><th>Type</th><th>Status</th><th>Rows / lines</th><th>Messages</th></tr></thead><tbody>{st.sources.map(s=><tr key={s.id}><td>{s.fileName}</td><td>{s.sourceType}</td><td><StatusBadge value={s.parseStatus}/></td><td>{s.rowCount ?? s.lines.length}</td><td>{s.parseMessages.join(" · ") || "Parsed"}</td></tr>)}</tbody></table></div> : <EmptyState title="No sources loaded" description="Load the fictional sample factory pack or import a supported text, CSV, or JSON export." />}</CardBody></Card></div>;
}

export function ReviewView() {
  const st = useApp();
  const [reason,setReason]=useState("Reviewed against cited fictional source evidence.");
  const pending=st.proposals.filter(p=>!p.review);
  return <div><PageHeader title="Knowledge review" description="Agent stages propose typed records. Only an engineer-reviewed, published version affects diagnosis." actions={<><Input className="w-72" value={reason} onChange={e=>setReason(e.target.value)} aria-label="Review reason"/><Button variant="primary" disabled={!st.proposals.some(p=>p.state==="APPROVED")} onClick={()=>void st.publishKnowledge(reason)}>Publish approved changes</Button></>} badges={<StatusBadge value={st.activeKnowledge().status}/>} />
    {st.pipelineStages.length ? <div className="mb-3 grid gap-2 md:grid-cols-5">{st.pipelineStages.map(s=><Card key={s.stage}><CardBody><p className="text-xs font-semibold">{s.stage.replace(/_/g," ")}</p><p className="mt-1 text-xs text-muted">{s.messages[0] ?? `${s.outputs.length} outputs`}</p></CardBody></Card>)}</div>:null}
    <div className="space-y-3">{st.proposals.map(p=><Card key={p.id}><CardHeader title={p.title} description={`${p.producedBy.replace(/_/g," ")} · ${p.evidence.length} cited span(s)`} actions={<StatusBadge value={p.state}/>} /><CardBody><p className="text-sm">{p.rationale}</p>{p.validation.errors.length ? <p className="mt-2 text-sm text-red">Blocked: {p.validation.errors.join(" ")}</p>:null}<div className="mt-3 flex flex-wrap gap-2"><Button variant="primary" disabled={!p.validation.ok || !!p.review} onClick={()=>st.reviewProposalAction(p.id,"APPROVED",reason)}>Approve</Button><Button disabled={!!p.review} onClick={()=>st.reviewProposalAction(p.id,"EVIDENCE_REQUESTED",reason)}>Request evidence</Button><Button variant="ghost" disabled={!!p.review} onClick={()=>st.reviewProposalAction(p.id,"REJECTED",reason)}>Reject</Button></div></CardBody></Card>)}</div>
    {!st.proposals.length ? <EmptyState title="No proposals yet" description="Load sources and run local compilation first." /> : pending.length===0 ? <p className="mt-3 text-sm text-muted">All proposals have a recorded review decision.</p>:null}</div>;
}

export function MatrixView() {
 const kv=useApp(s=>s.knowledgeVersions.find(k=>k.id===s.activeKnowledgeVersionId) ?? s.knowledgeVersions[0]);
 return <div><PageHeader title="Dependency matrix" description="The matrix and runtime use the same immutable published records." badges={<Badge tone="green">{kv.id}</Badge>} /><Card><CardBody className="overflow-x-auto"><table><thead><tr><th>From</th><th>Relation</th><th>To</th><th>Scope</th><th>Evidence</th><th>Status</th></tr></thead><tbody>{kv.edges.map(e=><tr key={e.id}><td><Link className="text-accent" href={`/plant/${e.from}`}>{e.from}</Link></td><td>{e.relation.replace(/_/g," ")}</td><td><Link className="text-accent" href={`/plant/${e.to}`}>{e.to}</Link></td><td>{[...e.applicableModes,...e.applicablePhases].join(", ")||"all"}</td><td>{e.evidenceRefs.length} span(s)</td><td><StatusBadge value={e.reviewStatus}/></td></tr>)}</tbody></table></CardBody></Card></div>;
}

export function IncidentsView() {
 const snapshot=useApp(s=>s.snapshot); const historical=useApp(s=>s.historicalIncidents);
 if(!snapshot)return <LoadingState label="Starting diagnosis engine…"/>;
 const items=[...snapshot.incidents,...historical];
 return <div><PageHeader title="Incidents" description="Observed conditions are separated from potentially affected assets and unsupported hypotheses." badges={<Badge tone="red">{snapshot.incidents.filter(i=>i.status!=="CLOSED"&&i.status!=="RESOLVED").length} active</Badge>} />{items.length?<div className="space-y-2">{items.map(i=><Link key={i.id} href={`/incidents/${i.id}`} className="block rounded-lg border border-border bg-surface p-4 hover:bg-surface-2"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="font-semibold">{i.title}</p><p className="mt-1 mono text-xs text-muted">{i.id} · {fmt(i.openedAt.ms)}</p></div><div className="flex gap-2"><StatusBadge value={i.diagnosis?.state}/><StatusBadge value={i.status}/></div></div><p className="mt-3 text-sm text-muted">{i.diagnosis?.summary ?? i.groupingRationale}</p><p className="mt-2 text-xs">Observed: {i.observedAssetIds.join(", ")||"—"} · Potentially affected: {i.potentiallyAffectedAssetIds.join(", ")||"—"}</p></Link>)}</div>:<EmptyState title="No incidents yet" description="Let the simulation advance. Incidents are created from observed deviations, not seeded UI counts." />}</div>;
}

export function IncidentView({id}:{id:string}) {
 const router=useRouter();
 const st=useApp(); const inc=st.snapshot?.incidents.find(i=>i.id===id)??st.historicalIncidents.find(i=>i.id===id);
 if(!st.snapshot)return <LoadingState label="Starting diagnosis engine…"/>; if(!inc)return <EmptyState title="Incident not found" description="This record may belong to a different browser-local workspace. Import its evidence bundle to restore it."/>;
 const d=inc.diagnosis; const draft=()=>{const wo=st.draftWorkOrderFromIncident(id); if(wo) router.push(`/maintenance/work-orders/${wo.id}`)};
 return <div><PageHeader title={inc.title} description={`${inc.id} · opened ${fmt(inc.openedAt.ms)}`} badges={<><StatusBadge value={inc.status}/><StatusBadge value={d?.state}/></>} actions={!inc.fixture?<Button variant="primary" disabled={!d} onClick={draft}><Wrench size={15}/>Create work order</Button>:undefined}/>
  <Card><CardHeader title="Situation" description="Conclusion first; evidence and limits remain inspectable."/><CardBody><p className="text-lg">{d?.summary??inc.groupingRationale}</p><div className="mt-3 grid gap-2 sm:grid-cols-3"><Metric label="Observed assets" value={inc.observedAssetIds.length} note={inc.observedAssetIds.join(", ")}/><Metric label="Potentially affected" value={inc.potentiallyAffectedAssetIds.length} note={inc.potentiallyAffectedAssetIds.join(", ")||"None asserted"}/><Metric label="Evidence gaps" value={d?.missingInputs.length??0} note={d?.missingInputs.join(" · ")||"None recorded"}/></div></CardBody></Card>
  {d?<><div className="mt-3 grid gap-3 lg:grid-cols-2"><Card><CardHeader title="Competing explanations"/><CardBody className="space-y-2">{d.candidates.map(c=><div key={c.family} className="rounded-md border border-border p-3"><div className="flex justify-between"><strong>#{c.rank} {c.title}</strong><span className="text-xs">{c.supportCount} support · {c.contradictionCount} contradict</span></div><p className="mt-1 text-sm text-muted">{c.mechanism}</p></div>)}</CardBody></Card><Card><CardHeader title="Next discriminating checks"/><CardBody className="space-y-2">{d.nextChecks.map(c=><div key={c.id} className="rounded-md bg-surface-2 p-3"><p className="font-medium">{c.title}</p><p className="text-xs text-muted">{c.safety}</p></div>)}</CardBody></Card></div>
  <Card className="mt-3"><CardHeader title="Evidence ledger" description={`Cutoff ${fmt(d.cutoffMs)} · knowledge ${d.knowledgeVersion}`}/><CardBody className="overflow-x-auto"><table><thead><tr><th>Evidence</th><th>Asset / tag</th><th>Observed</th><th>Reference</th><th>Quality</th></tr></thead><tbody>{d.evidence.map(e=><tr key={e.id}><td>{e.title}</td><td className="mono">{e.assetId} · {e.tagId}</td><td>{e.observedValue??"—"}</td><td>{e.referenceValue??"—"}</td><td><StatusBadge value={e.quality}/></td></tr>)}</tbody></table></CardBody></Card></>:null}</div>;
}

export function RecoveryListView(){const st=useApp();const runs=[...(st.snapshot?.runs??[]),...st.historicalRuns];return <div><PageHeader title="Recovery" description="A repair is an action; recovery is a separately observed, reviewed result."/><div className="grid gap-3 lg:grid-cols-2"><Card><CardHeader title="Plans"/><CardBody>{st.plans.length?st.plans.map(p=><Link className="mb-2 flex justify-between rounded-md border border-border p-3" href={`/recovery/${p.id}`} key={`${p.id}-${p.version}`}><span>{p.id} v{p.version}<span className="block text-xs text-muted">{p.checks.length} executable checks · {p.scope.recipe}</span></span><StatusBadge value={p.status}/></Link>):<p className="text-sm text-muted">Create a plan from an active incident.</p>}</CardBody></Card><Card><CardHeader title="Runs"/><CardBody>{runs.length?runs.map(r=><div key={r.id} className="mb-2 flex justify-between rounded-md border border-border p-3"><span>{r.id}<span className="block text-xs text-muted">{r.summary}</span></span><StatusBadge value={r.outcome}/></div>):<p className="text-sm text-muted">No recovery runs recorded.</p>}</CardBody></Card></div></div>}

export function RecoveryView({id}:{id:string}){const st=useApp();const versions=st.plans.filter(p=>p.id===id).sort((a,b)=>b.version-a.version);const p=versions[0];const runs=st.snapshot?.runs.filter(r=>r.planId===id)??[];if(!p)return <EmptyState title="Recovery plan not found" description="Create a recovery plan from an incident first."/>;return <div><PageHeader title={`Recovery plan ${p.id}`} description={`Version ${p.version} · ${p.scope.recipe} ${p.scope.mode} · ${p.warning}`} badges={<StatusBadge value={p.status}/>} actions={<>{p.status==="DRAFT"?<Button variant="primary" onClick={()=>st.approvePlanAction(p.id,"Approved for fictional demo execution")}>Approve plan</Button>:null}<Button variant="primary" disabled={p.status!=="APPROVED"} onClick={()=>void st.startRun(p.id)}>Run checks</Button></>}/><Card><CardHeader title="Executable checks" description={`${p.checks.length} checks compiled from ${p.knowledgeVersion}`}/><CardBody className="space-y-2">{p.checks.map(c=><div className="rounded-md border border-border p-3" key={c.id}><div className="flex justify-between"><strong>{c.kind.replace(/_/g," ")}</strong><span className="mono text-xs text-muted">{c.id}</span></div><p className="mt-1 text-xs text-muted">{p.checkJustifications[c.id]??c.requirementRef}</p></div>)}</CardBody></Card><Card className="mt-3"><CardHeader title="Observed runs"/><CardBody>{runs.map(r=><div key={r.id} className="mb-3 rounded-md border border-border p-3"><div className="flex justify-between"><strong>{r.id}</strong><StatusBadge value={r.outcome}/></div><p className="mt-1 text-sm text-muted">{r.summary}</p><div className="mt-2 grid gap-1 sm:grid-cols-2">{r.results.map(x=><div className="flex justify-between bg-surface-2 px-2 py-1 text-xs" key={x.checkId}><span>{x.checkId}</span><StatusBadge value={x.status}/></div>)}</div>{r.outcome!=="RUNNING"&&!r.reviewedBy?<Button className="mt-3" onClick={()=>st.reviewRun(r.id,"APPROVED","Reviewed observed check results")}>Record separate review</Button>:null}</div>)}{!runs.length?<p className="text-sm text-muted">Not run. No result is claimed before execution.</p>:null}</CardBody></Card></div>}

export function MaintenanceView(){const w=useApp(s=>s.workOrders);return <div><PageHeader title="Maintenance" description="Actions, approvals, inventory, and recovery evidence remain separate records."/><div className="space-y-2">{w.map(x=><Link href={`/maintenance/work-orders/${x.id}`} key={x.id} className="flex justify-between rounded-lg border border-border bg-surface p-4 hover:bg-surface-2"><span><strong>{x.title}</strong><span className="mt-1 block mono text-xs text-muted">{x.id} · {x.assetId} · {x.assignee}</span></span><div className="flex gap-2"><Badge tone={x.fixture?"grey":"accent"}>{x.fixture?"FICTIONAL FIXTURE":"CURRENT"}</Badge><StatusBadge value={x.state}/></div></Link>)}</div></div>}

export function WorkOrderView({id}:{id:string}){const router=useRouter();const st=useApp();const wo=st.workOrders.find(w=>w.id===id);const [intervention,setIntervention]=useState<InterventionId>("REPAIR_AIR_LEAK");if(!wo)return <EmptyState title="Work order not found" description="This work order is not available in this browser-local workspace."/>;const createPlan=()=>{if(!wo.incidentId)return;const p=st.createPlan(wo.incidentId,"TPL-CELL-A-FULL");if(p) router.push(`/recovery/${p.id}`)};return <div><PageHeader title={wo.title} description={`${wo.id} · ${wo.assetId} · ${wo.priority}`} badges={<StatusBadge value={wo.state}/>} actions={wo.fixture?undefined:<><Button onClick={()=>st.approveIntervention(id,"Approved for fictional demo maintenance")}>Approve intervention</Button><Button variant="primary" disabled={!wo.incidentId} onClick={createPlan}><ShieldCheck size={15}/>Build recovery plan</Button></>}/><div className="grid gap-3 lg:grid-cols-2"><Card><CardHeader title="Investigation and planned action"/><CardBody><p className="text-sm"><strong>Suspected:</strong> {wo.suspectedMechanism}</p><p className="mt-2 text-sm"><strong>Planned:</strong> {wo.plannedAction}</p>{!wo.fixture?<div className="mt-4 flex gap-2"><Select value={intervention} onChange={e=>setIntervention(e.target.value as InterventionId)}>{INTERVENTIONS.map(i=><option value={i.id} key={i.id}>{i.title}</option>)}</Select><Button variant="primary" onClick={()=>void st.recordWork(id,INTERVENTIONS.find(i=>i.id===intervention)?.description??intervention,intervention)}>Record work</Button></div>:null}</CardBody></Card><Card><CardHeader title="Recorded work"/><CardBody>{wo.workPerformed.map(x=><div className="mb-2 rounded-md bg-surface-2 p-3" key={x.id}><p>{x.description}</p><p className="text-xs text-muted">{x.by} · {fmt(x.at.ms)}</p></div>)}{!wo.workPerformed.length?<p className="text-sm text-muted">No work recorded. Recording a repair cannot set recovery to PASS.</p>:null}</CardBody></Card></div>{wo.testScope?<Card className="mt-3"><CardHeader title="Historical test scope" description="A prior scoped pass is not proof under untested conditions."/><CardBody><p className="text-sm"><strong>Tested:</strong> {wo.testScope.tested.join("; ")}</p><p className="mt-2 text-sm"><strong>Not tested:</strong> {wo.testScope.notTested.join("; ")}</p></CardBody></Card>:null}</div>}

export function InventoryView(){const st=useApp();return <div><PageHeader title="Inventory" description="Reservations and consumption use idempotent ledger transactions."/><Card><CardBody className="overflow-x-auto"><table><thead><tr><th>Part</th><th>On hand</th><th>Reserved</th><th>Minimum</th><th>Unit price</th></tr></thead><tbody>{st.inventory.map(p=><tr key={p.id}><td>{p.name}<span className="block mono text-xs text-muted">{p.id}</span></td><td>{p.onHand} {p.unit}</td><td>{p.reserved}</td><td>{p.minimumStock}</td><td>{money(p.catalogPricePaise)}</td></tr>)}</tbody></table></CardBody></Card></div>}

export function LabView(){const st=useApp();return <div><PageHeader title="Scenario lab" description="Deterministic seeded scenarios exercise the same runtime engine used by diagnosis and recovery."/ ><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{SCENARIOS.map(s=><Card key={s.id}><CardHeader title={`${s.number}. ${s.title}`} actions={st.workspace.scenarioId===s.id?<Badge tone="accent">ACTIVE</Badge>:undefined}/><CardBody><p className="text-sm text-muted">{s.story}</p><div className="mt-3 flex flex-wrap gap-1">{s.tags.map(t=><Badge tone="grey" key={t}>{t}</Badge>)}</div><Button className="mt-4" variant="primary" onClick={()=>void st.newDemoWorkspace(s.id,s.seed)}><Play size={14}/>Load scenario</Button></CardBody></Card>)}</div></div>}

export function EvaluationView(){const st=useApp();const r=st.evaluation;return <div><PageHeader title="Frozen evaluation" description="Same held-out episodes for baseline and complete engine; synthetic consistency is not field validation." actions={<Button variant="primary" disabled={st.evaluating} onClick={()=>void st.runEvaluation({seeds:EVALUATION_SEEDS,scenarioIds:SCENARIOS.map(s=>s.id),recovery:true})}>{st.evaluating?"Running…":"Run evaluation"}</Button>}/>{!r?<EmptyState title="Not run" description="No percentage is shown before the frozen multi-seed evaluation executes."/>:<Card><CardHeader title="Evaluation results" description={`${r.episodes.length} episodes · ran ${r.ranAt}`}/><CardBody><div className="grid gap-3 sm:grid-cols-3"><Metric label="Episodes" value={r.episodes.length}/><Metric label="Complete engine known matches" value={`${r.summary.engine.familyMatches} / ${r.summary.engine.knownCases}`}/><Metric label="Recovery false accepts" value={`${r.summary.recovery.engineFalseAccepts} / ${r.summary.recovery.negatives}`}/></div><pre className="mt-4 max-h-96 overflow-auto rounded-md bg-surface-2 p-3 text-xs">{JSON.stringify(r,null,2)}</pre></CardBody></Card>}</div>}

export function ReportsView(){const st=useApp();return <div><PageHeader title="Reports & evidence export" description="Exports retain IDs, versions, provenance, observations, work, cost assumptions, and review history." actions={<><Button onClick={()=>void st.exportTelemetryCsv()}><Download size={15}/>Telemetry CSV</Button><Button variant="primary" onClick={()=>void st.exportBundle()}><Download size={15}/>Evidence bundle</Button></>}/><Card><CardHeader title="Current session"/><CardBody className="grid gap-3 sm:grid-cols-3"><Metric label="Knowledge version" value={st.activeKnowledgeVersionId}/><Metric label="Audit events" value={st.audit.length}/><Metric label="Storage" value={st.storage.available?(st.storage.readOnly?"Read-only tab":"Browser local"):"Unavailable"}/></CardBody></Card><Button className="mt-3 no-print" onClick={()=>window.print()}>Print accessible report</Button></div>}

export function CostsView(){const st=useApp();const incidents=st.snapshot?.incidents??[];return <div><PageHeader title="Costs" description="Editable fictional assumptions. Downtime is interruption minutes × cell rate; overlapping intervals are not double-counted in domain calculations."/><div className="grid gap-3 md:grid-cols-2">{st.costAssumptions.map(c=>{const mins=incidents.flatMap(i=>i.interruptions.filter(x=>x.cellId===c.cellId)).reduce((n,x)=>n+Math.max(0,((x.endMs??st.snapshot?.clock.liveMs??x.startMs)-x.startMs)/60000),0);return <Card key={c.id}><CardHeader title={c.cellId}/><CardBody><Metric label="Illustrative interruption estimate" value={money(Math.round(mins*c.interruptionPaisePerMinute))} note={`${mins.toFixed(1)} cell-minutes × ${money(c.interruptionPaisePerMinute)}/min`}/><p className="mt-3 text-xs text-muted">{c.note}</p></CardBody></Card>})}</div></div>}

export function DataHealthView(){const st=useApp();const snap=st.snapshot;return <div><PageHeader title="Data health" description="Evidence quality states are explicit; missing numeric data remains null, never zero."/><div className="grid gap-3 sm:grid-cols-4"><Metric label="Observed tags" value={snap?.stats.tags??0}/><Metric label="Observations" value={snap?.stats.observations??0}/><Metric label="Unknown baselines" value={snap?.missingBaselines.length??0}/><Metric label="Live adapter" value="Not configured" note={snap?.liveAdapter.reason}/></div><Card className="mt-3"><CardHeader title="Import limitations"/><CardBody>{st.workspace.importInfo?.limitations.map((x,i)=><p className="mb-2 text-sm" key={i}>• {x}</p>)??<p className="text-sm text-muted">Demo simulation is active. These are generated observations, not factory telemetry.</p>}</CardBody></Card></div>}

export function SettingsView(){const st=useApp();const [q,setQ]=useState("");const matches=useMemo(()=>{const z=q.trim().toLowerCase();return z?TAGS.filter(t=>`${t.id} ${t.aliases.join(" ")} ${t.description}`.toLowerCase().includes(z)).slice(0,20):[]},[q]);return <div><PageHeader title="Settings & workspace" description="Local-first demo settings. No authenticated collaboration or cloud sync is claimed." actions={<Button variant="primary" onClick={()=>void st.persistNow()}>Save now</Button>}/><div className="grid gap-3 lg:grid-cols-2"><Card><CardHeader title="Execution"/><CardBody><p className="text-sm">Mode: <StatusBadge value={st.workspace.mode}/></p><p className="mt-3 text-sm">Active knowledge: <span className="mono">{st.activeKnowledgeVersionId}</span></p><p className="mt-3 text-sm">Persistence: {st.storage.available?"Stored in this browser — not cloud-synced.":st.storage.reason}</p><p className="mt-3 text-sm">Connected AI: optional server adapter; local deterministic workflow remains available without keys.</p></CardBody></Card><Card><CardHeader title="Registry search"/><CardBody><div className="relative"><Search className="absolute left-2 top-2" size={15}/><Input className="pl-8" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search tag aliases and descriptions"/></div>{matches.map(t=><Link className="mt-2 block rounded-md border border-border p-2 text-sm" href={`/plant/${t.assetId}`} key={t.id}><span className="mono">{t.id}</span><span className="block text-xs text-muted">{t.description}</span></Link>)}</CardBody></Card></div></div>}
