import type { FaultFamilyId, NextCheck } from "@/lib/domain/types";

/**
 * Small, inspectable diagnosis configuration. Evidence families are keys produced by
 * extractEvidence(). Each fault family lists which evidence supports or contradicts it,
 * which published dependency paths it needs, and what is deliberately NOT established.
 * There are no probabilities here; counts of independent evidence groups are shown as-is.
 */

export interface FamilyConfig {
  family: FaultFamilyId;
  title: string;
  mechanism: string;
  primary: string[];
  supports: string[];
  supportReason: Record<string, string>;
  contradicts: string[];
  contradictReason: Record<string, string>;
  absentContradicts: string[];
  absentReason: Record<string, string>;
  pendingIfAbsent: string[];
  pendingReason: Record<string, string>;
  unavailableFamilies: string[];
  unavailableReason: Record<string, string>;
  requiredPaths: Array<[string, string]>;
  notEstablished: string[];
  distinguishingCheckId?: string;
  supportedSummary: string;
}

export const FAMILY_CONFIG: FamilyConfig[] = [
  {
    family: "SHARED_PNEUMATIC_LOSS",
    title: "Shared pneumatic supply loss",
    mechanism: "Header pressure below the clamp prerequisite delays clamp proof in every fixture fed from the header.",
    primary: ["AIR", "CLAMP_A", "CLAMP_B"],
    supports: ["AIR", "CLAMP_A", "CLAMP_B"],
    supportReason: {
      AIR: "Shared header pressure is below the approved prerequisite.",
      CLAMP_A: "FIX-01 clamp delay follows the pressure deviation along DEP-AIR-FIX-01.",
      CLAMP_B: "CNC-02 clamp delay follows the pressure deviation along DEP-AIR-CNC-02.",
    },
    contradicts: [],
    contradictReason: {},
    absentContradicts: ["AIR"],
    absentReason: { AIR: "Header pressure stayed within the approved band; a shared pneumatic loss would show a pressure deviation." },
    pendingIfAbsent: [],
    pendingReason: {},
    unavailableFamilies: [],
    unavailableReason: {},
    requiredPaths: [["AIR-HDR-01", "FIX-01"]],
    notEstablished: ["A specific leak location or valve is not established; only the shared header deviation is observed.", "Compressor running status does not establish adequate air delivery."],
    distinguishingCheckId: "CHK-AIR-TREND",
    supportedSummary: "A shared air-pressure deviation precedes the clamp delays in the affected cell(s); check the shared utility evidence before replacing fixture sensors.",
  },
  {
    family: "LOCAL_FIXTURE_SENSOR",
    title: "Local fixture clamp-proof sensor fault",
    mechanism: "A fixture's own proof sensor fails while the header supply is adequate.",
    primary: ["CLAMP_A", "CLAMP_B"],
    supports: ["CLAMP_A", "CLAMP_B"],
    supportReason: { CLAMP_A: "FIX-01 clamp proof delayed.", CLAMP_B: "CNC-02 clamp proof delayed." },
    contradicts: ["AIR"],
    contradictReason: { AIR: "A shared pressure deviation explains the delay without a local sensor fault; two independent sensor faults coinciding with a pressure drop is not supported." },
    absentContradicts: [],
    absentReason: {},
    pendingIfAbsent: [],
    pendingReason: {},
    unavailableFamilies: [],
    unavailableReason: {},
    requiredPaths: [],
    notEstablished: ["No localized evidence (switch signal, pressure at the fixture) distinguishes a sensor fault from slow clamping."],
    distinguishingCheckId: "CHK-AIR-TREND",
    supportedSummary: "A clamp-proof delay is observed with header pressure in band; inspect the fixture's proof signal before replacing parts.",
  },
  {
    family: "COOLANT_DELIVERY_INADEQUATE",
    title: "Inadequate coolant delivery",
    mechanism: "Measured flow to the spindle falls while the pump reports running; bearing temperature rises after a delay.",
    primary: ["FLOW"],
    supports: ["FLOW", "TEMP"],
    supportReason: { FLOW: "Measured flow below band during CUTTING with run feedback TRUE.", TEMP: "Temperature rose after the flow deviation, consistent with the cooling edge's delayed response." },
    contradicts: [],
    contradictReason: {},
    absentContradicts: [],
    absentReason: {},
    pendingIfAbsent: ["TEMP"],
    pendingReason: { TEMP: "Thermal response lags flow loss by 30–180 s (DEP-PUMP-SPN-01); temperature evidence is pending, not contradictory." },
    unavailableFamilies: [],
    unavailableReason: {},
    requiredPaths: [["PUMP-01", "SPN-01"]],
    notEstablished: ["Filter restriction, valve state, or flow-measurement error are not distinguished by the available channels.", "Pump run feedback does not establish delivery."],
    distinguishingCheckId: "CHK-FLOW-VS-RUN",
    supportedSummary: "Measured coolant flow fell while the pump reported running; inadequate delivery is supported and temperature follows with a delay. The cause of the restriction is not established.",
  },
  {
    family: "SPINDLE_BEARING",
    title: "Spindle bearing degradation",
    mechanism: "Bearing damage raises friction, vibration, and temperature at matched speed.",
    primary: ["TEMP", "VIB_CELL-A"],
    supports: ["VIB_CELL-A", "CURRENT_CELL-A", "TEMP"],
    supportReason: { "VIB_CELL-A": "Vibration above band at matched speed.", "CURRENT_CELL-A": "Current above band at matched speed.", TEMP: "Temperature elevated." },
    contradicts: ["FLOW"],
    contradictReason: { FLOW: "A measured coolant flow loss explains the temperature rise without a bearing fault; bearing degradation is not supported by temperature alone." },
    absentContradicts: ["VIB_CELL-A"],
    absentReason: { "VIB_CELL-A": "Vibration is within band at matched speed; bearing degradation would raise it." },
    pendingIfAbsent: [],
    pendingReason: {},
    unavailableFamilies: [],
    unavailableReason: {},
    requiredPaths: [],
    notEstablished: ["No trained bearing fault classifier exists in PlantLens; this is a rule-based candidate only."],
    distinguishingCheckId: "CHK-MATCHED-VIB",
    supportedSummary: "Vibration, current, and temperature are elevated at matched speed with coolant delivery in band.",
  },
  {
    family: "MECHANICAL_LOAD_INCREASE",
    title: "Mechanical load increase (spindle)",
    mechanism: "Added resistance raises matched-condition current and vibration; reducing speed masks the symptom without removing it.",
    primary: ["CURRENT_CELL-A", "VIB_CELL-A", "CURRENT_CELL-B", "VIB_CELL-B"],
    supports: ["CURRENT_CELL-A", "VIB_CELL-A", "CURRENT_CELL-B", "VIB_CELL-B"],
    supportReason: {
      "CURRENT_CELL-A": "SPN-01 current above band at matched speed (drive channel).",
      "VIB_CELL-A": "SPN-01 vibration above band at matched speed (accelerometer channel).",
      "CURRENT_CELL-B": "SPN-02 current above band at matched speed.",
      "VIB_CELL-B": "SPN-02 vibration above band at matched speed.",
    },
    contradicts: [],
    contradictReason: {},
    absentContradicts: [],
    absentReason: {},
    pendingIfAbsent: [],
    pendingReason: {},
    unavailableFamilies: [],
    unavailableReason: {},
    requiredPaths: [],
    notEstablished: ["The specific mechanical cause (bearing, misalignment, tooling) is not established by current and vibration alone."],
    distinguishingCheckId: "CHK-MATCHED-VIB",
    supportedSummary: "Matched-condition current and vibration are above the approved band; a mechanical load increase is supported. A speed reduction would mask, not remove, it.",
  },
  {
    family: "COOLING_DEGRADATION",
    title: "Cooling degradation with mechanical component",
    mechanism: "Both reduced coolant delivery and added mechanical resistance are present.",
    primary: ["FLOW"],
    supports: ["FLOW", "CURRENT_CELL-A", "VIB_CELL-A"],
    supportReason: { FLOW: "Flow below band.", "CURRENT_CELL-A": "Current above band at matched speed — not explained by flow loss.", "VIB_CELL-A": "Vibration above band — not explained by flow loss." },
    contradicts: [],
    contradictReason: {},
    absentContradicts: ["CURRENT_CELL-A"],
    absentReason: { "CURRENT_CELL-A": "Current is within band; a compound mechanism would raise it." },
    pendingIfAbsent: [],
    pendingReason: {},
    unavailableFamilies: [],
    unavailableReason: {},
    requiredPaths: [["PUMP-01", "SPN-01"]],
    notEstablished: ["Restoring cooling alone will not clear the mechanical evidence; both must be verified separately."],
    distinguishingCheckId: "CHK-MATCHED-VIB",
    supportedSummary: "Flow loss and matched-condition mechanical deviations coexist; two mechanisms are retained.",
  },
  {
    family: "HANDSHAKE_ACK_UNRESOLVED",
    title: "Unresolved unload acknowledgement path",
    mechanism: "The robot completes its move, but the unload-complete acknowledgement CNC-01 waits for arrives late or not at all.",
    primary: ["ACK"],
    supports: ["ACK"],
    supportReason: { ACK: "move_complete observed; unload_complete outside the 8 s envelope." },
    contradicts: ["AIR", "SUPPLY"],
    contradictReason: { AIR: "Pressure deviation present; clamp delays could explain waiting instead.", SUPPLY: "Supply deviation present." },
    absentContradicts: [],
    absentReason: {},
    pendingIfAbsent: [],
    pendingReason: {},
    unavailableFamilies: [],
    unavailableReason: {},
    requiredPaths: [["ROB-01", "CNC-01"]],
    notEstablished: ["Whether the acknowledgement is absent (never written) or its logging channel is missing is not established from the trace alone."],
    distinguishingCheckId: "CHK-ACK-SOURCE",
    supportedSummary: "The robot reported movement complete, but the unload-complete acknowledgement exceeded the approved envelope while pressure and supply stayed in range. The acknowledgement path, not the robot mechanics, is the supported explanation.",
  },
  {
    family: "ROBOT_MECHANICAL",
    title: "Robot mechanical failure",
    mechanism: "The robot fails to complete its motion.",
    primary: ["ACK"],
    supports: [],
    supportReason: {},
    contradicts: ["ACK"],
    contradictReason: { ACK: "move_complete was observed from the robot controller; the motion completed." },
    absentContradicts: [],
    absentReason: {},
    pendingIfAbsent: [],
    pendingReason: {},
    unavailableFamilies: [],
    unavailableReason: {},
    requiredPaths: [],
    notEstablished: ["No robot mechanical channel (torque, position error) is instrumented."],
    distinguishingCheckId: "CHK-ACK-SOURCE",
    supportedSummary: "",
  },
  {
    family: "SUPPLY_SAG",
    title: "Shared electrical supply sag",
    mechanism: "Feeder voltage drop propagates to cabinets along electrical edges; current rises for constant power.",
    primary: ["SUPPLY"],
    supports: ["SUPPLY", "CABINET_CELL-A", "CABINET_CELL-B"],
    supportReason: { SUPPLY: "Feeder voltage below 380 V.", "CABINET_CELL-A": "CNC-01 cabinet voltage follows the feeder (DEP-FDR-CNC-01).", "CABINET_CELL-B": "CNC-02 cabinet voltage follows the feeder (DEP-FDR-CNC-02)." },
    contradicts: [],
    contradictReason: {},
    absentContradicts: [],
    absentReason: {},
    pendingIfAbsent: [],
    pendingReason: {},
    unavailableFamilies: ["COMP_VOLTAGE"],
    unavailableReason: { COMP_VOLTAGE: "Compressor and chiller voltages are not instrumented; downstream effect on them is unobserved." },
    requiredPaths: [["FDR-01", "CNC-01"]],
    notEstablished: ["The supply sag does not explain vibration deviations; those remain separate."],
    distinguishingCheckId: "CHK-SUPPLY-DOWNSTREAM",
    supportedSummary: "A feeder voltage sag propagates to the machine cabinets along the approved electrical edges. It explains the electrical alarms, not every alarm.",
  },
  {
    family: "SENSOR_SUSPECT",
    title: "Sensor or channel fault",
    mechanism: "A measurement channel reports a value that does not respond to operating context, or is missing.",
    primary: ["TEMP_SUSPECT", "FLOW_MISSING"],
    supports: [],
    supportReason: {},
    contradicts: [],
    contradictReason: {},
    absentContradicts: [],
    absentReason: {},
    pendingIfAbsent: [],
    pendingReason: {},
    unavailableFamilies: [],
    unavailableReason: {},
    requiredPaths: [],
    notEstablished: ["Constancy is a reason for a sensor check, not universal proof of sensor failure."],
    distinguishingCheckId: "CHK-SENSOR",
    supportedSummary: "",
  },
  {
    family: "UNSUPPORTED_ANOMALY",
    title: "Anomaly without an approved explanatory model",
    mechanism: "The observed deviation has no rule in the library linking it to machine evidence.",
    primary: ["GAUGE"],
    supports: [],
    supportReason: {},
    contradicts: [],
    contradictReason: {},
    absentContradicts: [],
    absentReason: {},
    pendingIfAbsent: [],
    pendingReason: {},
    unavailableFamilies: [],
    unavailableReason: {},
    requiredPaths: [],
    notEstablished: ["Material, tooling, measurement, and recipe factors are all possible; none is supported by the available rules and evidence."],
    distinguishingCheckId: "CHK-REQUEST-EVIDENCE",
    supportedSummary: "",
  },
];

export const NEXT_CHECK_LIBRARY: NextCheck[] = [
  {
    id: "CHK-AIR-TREND",
    title: "Inspect the shared header pressure trend against both clamp acknowledgements",
    kind: "EVIDENCE_INSPECTION",
    prerequisites: ["AIR-HDR-01.header_pressure GOOD", "clamp_proof events from both cells"],
    distinguishes: ["SHARED_PNEUMATIC_LOSS", "LOCAL_FIXTURE_SENSOR"],
    interpretation: [
      { result: "Pressure below 5.5 bar precedes both clamp delays", meaning: "Shared pneumatic loss supported; do not replace two fixture sensors." },
      { result: "Pressure in band while one fixture delays", meaning: "Local fixture cause more likely; inspect that fixture's proof signal." },
    ],
    safety: "Evidence inspection only. No machine interaction.",
    target: { route: "/incidents", label: "Open timeline" },
  },
  {
    id: "CHK-FLOW-VS-RUN",
    title: "Compare measured flow with pump run feedback during CUTTING",
    kind: "EVIDENCE_INSPECTION",
    prerequisites: ["PUMP-01.coolant_flow GOOD", "PUMP-01.run_feedback"],
    distinguishes: ["COOLANT_DELIVERY_INADEQUATE", "SPINDLE_BEARING"],
    interpretation: [
      { result: "Run TRUE, flow below band", meaning: "Delivery inadequate despite running pump; temperature rise expected to follow." },
      { result: "Run TRUE, flow in band, temperature high", meaning: "Cooling delivery is not the explanation; mechanical candidates gain weight." },
      { result: "Flow channel MISSING", meaning: "Delivery cannot be asserted either way." },
    ],
    safety: "Evidence inspection only.",
    target: { route: "/incidents", label: "Open evidence" },
  },
  {
    id: "CHK-MATCHED-VIB",
    title: "Compare current and vibration at the approved recipe speed",
    kind: "EVIDENCE_INSPECTION",
    prerequisites: ["Commanded speed equals the approved recipe speed", "CUTTING phase samples"],
    distinguishes: ["MECHANICAL_LOAD_INCREASE", "COOLING_DEGRADATION", "SPINDLE_BEARING"],
    interpretation: [
      { result: "Elevated at matched speed", meaning: "Mechanical load increase supported." },
      { result: "Normal only at reduced speed", meaning: "Symptom masked by context change; not comparable to the baseline." },
    ],
    safety: "Evidence inspection only. Do not change setpoints to make charts look better.",
    target: { route: "/incidents", label: "Open evidence" },
  },
  {
    id: "CHK-ACK-SOURCE",
    title: "Inspect the acknowledgement source and event ordering",
    kind: "EVIDENCE_INSPECTION",
    prerequisites: ["ROB-01.move_complete and ROB-01.unload_complete lanes", "Clock contract between robot controller and PLC"],
    distinguishes: ["HANDSHAKE_ACK_UNRESOLVED", "ROBOT_MECHANICAL"],
    interpretation: [
      { result: "move_complete present, unload_complete late/absent", meaning: "Acknowledgement path unresolved; robot motion completed." },
      { result: "move_complete absent", meaning: "Robot motion did not complete; a different investigation." },
      { result: "Clock uncertainty wider than the gap", meaning: "Ordering cannot be established; fix the clock contract first." },
    ],
    safety: "Evidence inspection only. Never bypass the interlock.",
    target: { route: "/incidents", label: "Open event lanes" },
  },
  {
    id: "CHK-SUPPLY-DOWNSTREAM",
    title: "Compare downstream cabinet voltages after the feeder recovers",
    kind: "EVIDENCE_INSPECTION",
    prerequisites: ["FDR-01.supply_voltage", "CNC-01/CNC-02 cabinet voltage"],
    distinguishes: ["SUPPLY_SAG", "MECHANICAL_LOAD_INCREASE"],
    interpretation: [
      { result: "Cabinets recover with the feeder; vibration stays high on one spindle", meaning: "The residual deviation is independent of the supply." },
      { result: "Everything recovers", meaning: "All alarms explained by the sag." },
    ],
    safety: "Evidence inspection only.",
    target: { route: "/incidents", label: "Open evidence" },
  },
  {
    id: "CHK-SENSOR",
    title: "Sensor check on the flagged channel",
    kind: "SIMULATED_CHECK",
    prerequisites: ["Channel flagged MISSING or SUSPECT"],
    distinguishes: ["SENSOR_SUSPECT", "COOLANT_DELIVERY_INADEQUATE"],
    interpretation: [
      { result: "Channel responds to context after restoration", meaning: "Evidence valid again; rerun the recovery suite." },
      { result: "Channel stays constant", meaning: "Do not use it as evidence." },
    ],
    safety: "Simulated instrument check; in a real plant follow the site's instrument procedure.",
    target: { route: "/data-health", label: "Open data health" },
  },
  {
    id: "CHK-REQUEST-EVIDENCE",
    title: "Request source and evidence coverage for this asset",
    kind: "EVIDENCE_INSPECTION",
    prerequisites: [],
    distinguishes: ["UNSUPPORTED_ANOMALY"],
    interpretation: [{ result: "A reviewed rule links the result to machine evidence", meaning: "The anomaly can then be diagnosed; until then it stays UNKNOWN." }],
    safety: "Knowledge request only.",
    target: { route: "/knowledge/review", label: "Open knowledge review" },
  },
];
