import { describe, expect, it } from "vitest";
import { approveProposalChange, createCadDocument, deterministicDraft, validateConnection } from "@/lib/cad";

describe("CAD engineering document", () => {
  it("uses shared asset IDs across all three synchronized views", () => { const doc = createCadDocument(); const motor = doc.placements.filter(p => p.assetId === "M-101").map(p => p.view); expect(motor).toEqual(expect.arrayContaining(["electrical", "presentation"])); expect(new Set(doc.assets.map(a => a.id)).size).toBe(doc.assets.length); });
  it("marks electrical starting connections as illustrative templates", () => { const doc = createCadDocument(); expect(doc.connections.filter(c => c.view === "electrical")).not.toHaveLength(0); expect(doc.connections.filter(c => c.view === "electrical").every(c => c.verification === "TEMPLATE")).toBe(true); });
  it("does not manufacture verification or source evidence in seeded signal paths", () => { const doc = createCadDocument(); expect(doc.connections.filter(c => c.view === "signal").every(c => c.verification === "UNVERIFIED")).toBe(true); expect(doc.connections.map(c => c.evidence ?? "").join(" ")).not.toMatch(/approved binding|imported loop schedule/i); });
  it("blocks incompatible typed connections", () => { const doc = createCadDocument(); expect(validateConnection(doc, { view: "signal", sourceTerminalId: "T-VFD-TX", targetTerminalId: "T-UNO-A0", signalType: "telemetry", unit: "Hz" })).toContain("Signal types are incompatible."); });
  it("drafts and individually approves the supported offline rename intent", () => { const doc = createCadDocument(); const proposal = deterministicDraft("rename M-101 to Main pump motor", doc); const pending = { ...doc, proposals: [proposal] }; const next = approveProposalChange(pending, proposal.id, proposal.changes[0].id); expect(next.assets.find(a => a.id === "M-101")?.name).toBe("Main pump motor"); expect(next.proposals[0].changes[0].status).toBe("APPROVED"); expect(next.revision).toBe(doc.revision + 1); });
  it("does not pretend unsupported offline requests succeeded", () => { const proposal = deterministicDraft("calculate a breaker rating from the picture", createCadDocument()); expect(proposal.status).toBe("BLOCKED"); expect(proposal.changes).toEqual([]); expect(proposal.message).toMatch(/Local AI is unavailable/); });
  it("blocks stale and malformed proposal changes", () => { const doc = createCadDocument(); const stale = deterministicDraft("rename M-101 to Main motor", doc); const changed = { ...doc, revision: doc.revision + 1, proposals: [stale] }; expect(approveProposalChange(changed, stale.id, stale.changes[0].id).proposals[0].status).toBe("BLOCKED"); const add = deterministicDraft("add sensor PT-202 named Suction pressure", doc); add.changes[0].value = "not-json"; expect(approveProposalChange({ ...doc, proposals: [add] }, add.id, add.changes[0].id).proposals[0].status).toBe("BLOCKED"); });
});
