import { describe, expect, it } from "vitest";
import { approveEngineeringProposal, previewEngineeringValue, validateEngineeringBinding, validateLiveEngineeringSample, type EngineeringBinding, type EngineeringState } from "@/lib/engineering";
import type { ChannelDescriptor } from "@/lib/live";

const channel: ChannelDescriptor = { id: "vfd.frequency", label: "Frequency", dataType: "UINT16", sourceKind: "MODBUS_RTU", rawUnit: "0.01 Hz", samplingRateHz: 2, calibrationRevision: 0, access: "READ_ONLY", mappingStatus: "UNMAPPED", registerAddress: 100 };
const context = { advertisedChannels: [channel], deviceUuid: "11111111-1111-4111-8111-111111111111", schemaHash: "a".repeat(64) };
const binding = (): EngineeringBinding => ({ id: "B-1", assetId: "VFD-1", deviceUuid: context.deviceUuid, schemaHash: context.schemaHash, channelId: channel.id, signal: "frequency", dataType: "UINT16", sourceUnit: "0.01 Hz", canonicalUnit: "Hz", scale: 0.01, offset: 0, range: { min: 0, max: 60 }, cadenceMs: 500, state: "PROPOSED", createdAtMs: 1, createdBy: "Engineer", modbus: { deviceModel: "ACME Drive X100-2K2", address: 100, functionCode: 3, evidence: { id: "MAN-1:p42", title: "ACME X100 Modbus Manual", url: "https://manufacturer.example/x100.pdf", official: true } } });

describe("engineering register bindings", () => {
  it("normalizes deterministically and marks stale or out-of-range samples", () => { const b = binding(); expect(previewEngineeringValue(b, { value: 5000, atMs: 1_000, quality: "GOOD" }, 1_100)?.normalized).toBe(50); expect(previewEngineeringValue(b, { value: 7000, atMs: 1_000, quality: "GOOD" }, 1_100)?.quality).toBe("OUT_OF_RANGE"); expect(previewEngineeringValue(b, { value: 5000, atMs: 1_000, quality: "GOOD" }, 2_001)?.quality).toBe("STALE"); expect(previewEngineeringValue(b, undefined, 2_001)).toBeNull(); });
  it("rejects invalid units, scale, range, cadence, and unknown channels", () => { const bad = { ...binding(), sourceUnit: "rpm", scale: 0, range: { min: 2, max: 1 }, cadenceMs: 1 }; const errors = validateEngineeringBinding(bad, context).errors.join(" "); expect(errors).toMatch(/Source unit/); expect(errors).toMatch(/Scale/); expect(errors).toMatch(/Range/); expect(errors).toMatch(/Cadence/); expect(validateEngineeringBinding({ ...binding(), channelId: "invented" }, context).errors.join(" ")).toMatch(/not advertised/); });
  it("blocks unadvertised or unsupported register reads", () => { const wrong = binding(); wrong.modbus = { ...wrong.modbus!, address: 101, functionCode: 6 as 3 }; const errors = validateEngineeringBinding(wrong, context).errors.join(" "); expect(errors).toMatch(/exactly match/); expect(errors).toMatch(/Only read-only/); });
  it("requires an exact model and official cited evidence", () => { const uncited = binding(); uncited.modbus = { ...uncited.modbus!, deviceModel: "unknown", evidence: { ...uncited.modbus!.evidence, id: "", url: "file:///manual.pdf" } }; const errors = validateEngineeringBinding(uncited, context).errors.join(" "); expect(errors).toMatch(/exact device model/); expect(errors).toMatch(/official HTTPS/); });
  it("approves one valid proposal and rejects version conflicts", () => { const b = binding(); const state: EngineeringState = { schemaVersion: 1, revision: 4, bindings: [], proposals: [{ id: "P-1", baseRevision: 4, status: "IN_REVIEW", binding: b, validation: { errors: [], warnings: [] } }] }; const next = approveEngineeringProposal(state, "P-1", "Engineer", 5, context); expect(next.revision).toBe(5); expect(next.bindings[0]).toMatchObject({ state: "APPROVED", approvedBy: "Engineer" }); expect(() => approveEngineeringProposal({ ...state, revision: 5 }, "P-1", "Engineer", 5, context)).toThrow(/Version conflict/); });
  it("pins the device identity and schema", () => { expect(validateEngineeringBinding({ ...binding(), schemaHash: "b".repeat(64) }, context).errors.join(" ")).toMatch(/schema hash/); });
  it("blocks arbitrary or dimensionally unsupported conversions", () => { expect(validateEngineeringBinding({ ...binding(), sourceUnit: "V", canonicalUnit: "rpm", scale: 60 }, context).errors.join(" ")).toMatch(/Unsupported unit conversion/); expect(validateEngineeringBinding({ ...binding(), sourceUnit: "V", canonicalUnit: "V", scale: 2 }, context).errors.join(" ")).toMatch(/Same-unit bindings require identity/); });
  it("requires a finite, correctly typed, current nonfuture GOOD sample", () => { const b = binding(); expect(validateLiveEngineeringSample(b, { value: 5000, atMs: 1_000, quality: "GOOD" }, 1_200)).toEqual([]); const future = validateLiveEngineeringSample(b, { value: Number.NaN, atMs: 2_000, quality: "GOOD" }, 1_200).join(" "); expect(future).toMatch(/future/i); expect(future).toMatch(/numeric/i); const stale = validateLiveEngineeringSample(b, { value: "5000", atMs: 1_000, quality: "STALE" }, 2_100).join(" "); expect(stale).toMatch(/stale/i); expect(stale).toMatch(/numeric/i); });
});
