"use client";

import Link from "next/link";
import { ArrowDown, ArrowRight, Check, CircleHelp, Clock3, Database, GitBranch, Layers3, Scale, ShieldAlert, Sparkles, X } from "lucide-react";
import { Badge, Button, Card, CardBody, CardHeader } from "@/components/ui";

const hypotheses = [
  { name: "Mechanical load increase", state: "STRONGLY SUPPORTED", tone: "green" as const, score: 92, detail: "Current and vibration rise together at matched speed; voltage remains normal." },
  { name: "Bearing degradation", state: "POSSIBLE", tone: "amber" as const, score: 56, detail: "Some mechanical evidence fits, but the available channels do not isolate a bearing." },
  { name: "Cooling loss", state: "WEAK", tone: "grey" as const, score: 27, detail: "Temperature can fit, but normal coolant flow contradicts the proposed path." },
  { name: "Supply sag", state: "CONTRADICTED", tone: "red" as const, score: 7, detail: "The approved supply-sag path expects low voltage; observed voltage is normal and GOOD quality." },
];

const evidence = [
  ["Supply voltage", "415 V", "NORMAL", "GOOD", "contradicts sag"],
  ["Motor current", "18.7 A", "HIGH", "GOOD", "supports load"],
  ["Actual speed", "1448 rpm", "IN BAND", "GOOD", "context matched"],
  ["Vibration RMS", "4.2 mm/s", "HIGH", "GOOD", "supports mechanical"],
  ["Bearing temperature", "rising later", "HIGH", "GOOD", "timing consistent"],
];

function Flow({ title, nodes, tone }: { title: string; nodes: string[]; tone: "accent" | "amber" | "red" }) {
  const colors = tone === "accent" ? "border-accent/30 bg-accent-soft text-accent" : tone === "amber" ? "border-amber/30 bg-amber-soft text-amber" : "border-red/30 bg-red-soft text-red";
  return <div className="rounded-xl border border-border bg-surface p-4"><p className="mb-4 text-xs font-semibold uppercase tracking-[.14em] text-muted">{title}</p><div className="flex flex-col items-stretch">{nodes.map((n,i)=><div key={n} className="contents"><div className={`rounded-lg border px-3 py-2 text-center text-sm font-medium ${colors}`}>{n}</div>{i<nodes.length-1?<ArrowDown className="mx-auto my-1 text-muted" size={16}/>:null}</div>)}</div></div>;
}

export default function ExplainPage() {
  return <div className="mx-auto max-w-7xl">
    <div className="relative mb-6 overflow-hidden rounded-2xl border border-accent/20 bg-surface p-6 md:p-9">
      <div className="absolute -right-20 -top-24 h-64 w-64 rounded-full bg-accent-soft blur-3xl" />
      <div className="relative grid items-end gap-8 lg:grid-cols-[1.4fr_.6fr]">
        <div><Badge tone="accent">JUDGE EXPLAINER · 3 MINUTES</Badge><h1 className="mt-4 max-w-4xl text-3xl font-semibold leading-tight tracking-tight md:text-5xl">How does PlantLens decide what caused a stoppage?</h1><p className="mt-4 max-w-3xl text-base leading-relaxed text-muted md:text-lg">The graph does not magically choose. It defines which evidence each fault should produce. The runtime compares quality-gated observations with those approved causal paths, rewards support, penalizes valid contradictions more heavily, and abstains when evidence cannot separate the leaders.</p><div className="mt-5 flex flex-wrap gap-2"><Link href="/lab"><Button variant="primary">Open live scenarios <ArrowRight size={15}/></Button></Link><Link href="/knowledge/matrix"><Button>Inspect approved dependencies</Button></Link></div></div>
        <div className="rounded-xl border border-border bg-surface-2 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-muted">The honest output</p><p className="mt-3 text-2xl font-semibold text-green">Strongly supported</p><p className="mt-2 text-sm text-muted">A relative, inspectable ranking—not “94.73% probability.” The prototype is not probability-calibrated on field incidents.</p></div>
      </div>
    </div>

    <section className="mb-8"><div className="mb-3 flex items-center gap-2"><Database size={18} className="text-accent"/><h2 className="text-xl font-semibold">1. First, turn signals into comparable evidence</h2></div><p className="mb-4 max-w-4xl text-sm text-muted">PlantLens does not ask whether 18.7 A is universally “high.” It asks whether it is abnormal for this asset, recipe, phase, speed, and approved baseline. Missing data stays missing; it never becomes a zero or a normal reading.</p><Card><CardBody className="overflow-x-auto"><table><thead><tr><th>Observation</th><th>Value</th><th>Evidence state</th><th>Quality gate</th><th>Interpretation</th></tr></thead><tbody>{evidence.map(r=><tr key={r[0]}>{r.map((x,i)=><td key={i}>{i===2?<Badge tone={x==="HIGH"?"red":"green"}>{x}</Badge>:i===3?<Badge tone="green">{x}</Badge>:x}</td>)}</tr>)}</tbody></table></CardBody></Card></section>

    <section className="mb-8"><div className="mb-3 flex items-center gap-2"><GitBranch size={18} className="text-accent"/><h2 className="text-xl font-semibold">2. Each hypothesis predicts a different fingerprint</h2></div><div className="grid gap-3 md:grid-cols-3"><Flow title="H1 · Mechanical load" tone="accent" nodes={["Mechanical resistance", "Torque demand ↑", "Current + vibration ↑", "Temperature ↑ later"]}/><Flow title="H2 · Supply sag" tone="red" nodes={["Supply voltage ↓", "Torque capability affected", "Drive response changes", "Possible speed deviation"]}/><Flow title="H3 · Bearing condition" tone="amber" nodes={["Friction / impacts", "Vibration signature ↑", "Possible acoustic change", "Temperature may rise"]}/></div></section>

    <section className="mb-8 grid gap-4 lg:grid-cols-[.8fr_1.2fr]"><Card><CardHeader title="The implemented prototype rule" description="What the current demo actually executes"/><CardBody><div className="rounded-lg bg-surface-2 p-4 font-mono text-sm"><p>candidate score =</p><p className="mt-2 text-green">support groups</p><p className="text-red">− 2 × contradiction groups</p></div><ul className="mt-4 space-y-3 text-sm"><li className="flex gap-2"><Check className="shrink-0 text-green" size={17}/>Correlated channels are grouped so they are not counted as independent witnesses.</li><li className="flex gap-2"><X className="shrink-0 text-red" size={17}/>A strong, valid contradiction outweighs a weak correlation.</li><li className="flex gap-2"><CircleHelp className="shrink-0 text-grey" size={17}/>Unavailable evidence is counted as unavailable—not against the hypothesis.</li><li className="flex gap-2"><ShieldAlert className="shrink-0 text-amber" size={17}/>Close candidates produce AMBIGUOUS and a next check, not a forced winner.</li></ul></CardBody></Card>
      <Card><CardHeader title="Illustrative ranking" description="Labels are defensible; bars are relative display strength, not probabilities."/><CardBody className="space-y-4">{hypotheses.map(h=><div key={h.name}><div className="mb-1 flex flex-wrap items-center justify-between gap-2"><span className="font-medium">{h.name}</span><Badge tone={h.tone}>{h.state}</Badge></div><div className="h-2 overflow-hidden rounded-full bg-surface-2"><div className={`h-full rounded-full ${h.tone==="green"?"bg-green":h.tone==="red"?"bg-red":h.tone==="amber"?"bg-amber":"bg-grey"}`} style={{width:`${h.score}%`}}/></div><p className="mt-1 text-xs text-muted">{h.detail}</p></div>)}</CardBody></Card></section>

    <section className="mb-8"><div className="mb-3 flex items-center gap-2"><Clock3 size={18} className="text-accent"/><h2 className="text-xl font-semibold">3. Timing, topology, and context stop shallow guesses</h2></div><div className="grid gap-3 md:grid-cols-3"><Card><CardBody><Clock3 className="text-accent"/><h3 className="mt-3 font-semibold">Temporal order</h3><p className="mt-2 text-sm text-muted">Current may change immediately while temperature rises later. If clock uncertainty overlaps the event gap, PlantLens marks ordering unresolved.</p></CardBody></Card><Card><CardBody><Layers3 className="text-accent"/><h3 className="mt-3 font-semibold">Plant topology</h3><p className="mt-2 text-sm text-muted">Three dependent machines changing together favors one approved shared feeder path over three unrelated local failures.</p></CardBody></Card><Card><CardBody><Scale className="text-accent"/><h3 className="mt-3 font-semibold">Operating context</h3><p className="mt-2 text-sm text-muted">A recipe or load change can explain higher current. Evidence is compared only with the approved baseline for matching conditions.</p></CardBody></Card></div></section>

    <section className="mb-8 rounded-2xl border border-border bg-surface p-5 md:p-7"><div className="grid gap-6 lg:grid-cols-2"><div><Badge tone="amber">CALIBRATION ROADMAP · NOT CURRENT PROBABILITIES</Badge><h2 className="mt-3 text-xl font-semibold">From transparent rules to calibrated weights</h2><p className="mt-3 text-sm leading-relaxed text-muted">The next scoring layer can give each approved relationship an engineer-defined importance, abnormality strength, data quality, context match, and timing consistency. Those remain illustrative until historical labeled incidents are sufficient to estimate and validate them.</p><div className="mt-4 rounded-lg bg-surface-2 p-4 font-mono text-sm"><p>contribution(h,e) = W × A × Q × M × T</p><p className="mt-2">rank(h) = support + timing + topology + context − λ·contradiction</p><p className="mt-2 text-red">λ &gt; 1</p></div></div><div><p className="text-xs font-semibold uppercase tracking-wider text-muted">Three things stay separate</p><div className="mt-3 space-y-2">{[["Graph structure","What can cause what? Versioned and engineer approved."],["Scoring configuration","Importance, contradiction penalty, and timing windows."],["Runtime evidence","What actually happened in this incident, with quality and provenance."]].map(([a,b],i)=><div className="flex gap-3 rounded-lg border border-border p-3" key={a}><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-accent-soft font-semibold text-accent">{i+1}</span><div><strong>{a}</strong><p className="text-sm text-muted">{b}</p></div></div>)}</div></div></div></section>

    <section className="mb-6 rounded-2xl bg-[#171614] p-6 text-white md:p-8"><div className="flex items-center gap-2 text-[#9db5ff]"><Sparkles size={18}/><span className="text-xs font-semibold uppercase tracking-[.15em]">20-second jury answer</span></div><blockquote className="mt-4 max-w-5xl text-lg leading-relaxed md:text-2xl">“The approved dependency graph defines the evidence expected for each fault. At runtime we quality-gate and context-match observations, traverse backward to candidate causes, reward supporting evidence and heavily penalize valid contradictions. Missing evidence is never treated as normal. When the leaders are too close, PlantLens abstains and recommends the approved check that best separates them. The current score is a transparent relative ranking, not a fake probability.”</blockquote></section>
  </div>;
}
